version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 12345:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid